### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by ZackWhiteIT** [treyhunner/names#26]
```
Traceback (most recent call last):
  File ".\foo\bar.py", line 12, in <module>
    import names
  File "..\venv\lib\site-packages\names\__init__.py", line 39
    print get_full_name()
          ^
SyntaxError: invalid syntax
```

**Comment by JavaIsPain** [comment]
Looks like you are trying to execute an old version of the script with python3. Are you sure you are using 0.3?
